GET http://localhost:3000/api/subscribers

###

GET http://localhost:3000/api/subscribers/5f716144d982b3577888b9b6

###

POST http://localhost:3000/api/subscribers
Content-Type: application/json 

{
    "name": "AmazingPerson69420",
    "subscribersToChannel": "Web Dev Simply"
}

###

DELETE http://localhost:3000/api/subscribers/5f7a50827a7bf17a1801f879

###

PATCH  http://localhost:3000/api/subscribers/5f716144d982b3577888b9b6
Content-Type: application/json

{
    "name": "b2"
}